create or replace view ES_ERP_END_RIGHT_JOIN_OPEN(
	CONTRACT_MAKLSYNCDATE,
	UNION_FLAG,
	MONTH_ID,
	CONTRACT_NUM,
	CONTRACTID,
	PRODUCT_CLASS,
	ITEM_PROD,
	ITEM_EDITION_ID,
	SALES_AMOUNT,
	DISCOUNT_EXPIRY_ARR,
	PRICE_CHANGE,
	CLOSE_ARR,
	OPEN_ARR,
	NEW_LOGO_FLAG,
	REVISION_FLAG,
	CHURN_MONTH_FLAG,
	REVISION_CHANGE_FLAG,
	CONTRACT_ITEM_MONTH_END_FLAG,
	REVISION_NUMBER_END_MONTH,
	SUB_ACCOUNT,
	PARTNER_ACCOUNT_FLAG,
	CLOSE_QTY,
	OPEN_QTY,
	UOM
) as (

SELECT
"MONTH_OPEN"."MAKLSYNCDATE" "CONTRACT_MAKLSYNCDATE"
, 0 "UNION_FLAG"
, (("YEAR"("MONTH_OPEN"."NEXT_MID") * 100) + "MONTH"("MONTH_OPEN"."NEXT_MID")) "MONTH_ID"
, "MONTH_OPEN"."CONTRACTNUM" "CONTRACT_NUM"
, "MONTH_OPEN"."CONTRACTID"
, "MONTH_OPEN"."PRODUCT_CLASS"
, "MONTH_OPEN"."ITEM_PROD" "ITEM_PROD"
, "MONTH_OPEN"."USRMAKLEDITIONID" "ITEM_EDITION_ID"
, COALESCE((CASE WHEN ((COALESCE("MONTH_END"."CLOSE_ARR", 0) <> 0) OR (COALESCE("MONTH_OPEN"."CLOSE_ARR", 0) <> 0)) THEN "MONTH_END"."SALES_AMOUNT" END), 0) "SALES_AMOUNT"
, COALESCE((CASE WHEN ((COALESCE("MONTH_END"."CLOSE_ARR", 0) <> 0) OR (COALESCE("MONTH_OPEN"."CLOSE_ARR", 0) <> 0)) THEN "MONTH_END"."DISCOUNT_EXPIRY_ARR" END), 0) "DISCOUNT_EXPIRY_ARR"
, COALESCE((CASE WHEN ((COALESCE("MONTH_END"."CLOSE_ARR", 0) <> 0) OR (COALESCE("MONTH_OPEN"."CLOSE_ARR", 0) <> 0)) THEN "MONTH_END"."PRICE_CHANGE" END), 0) "PRICE_CHANGE"
, COALESCE("MONTH_END"."CLOSE_ARR", 0) "CLOSE_ARR"
, COALESCE("MONTH_OPEN"."CLOSE_ARR", 0) "OPEN_ARR"
, COALESCE("MONTH_END"."CONTRACT_NEW_FLAG", 0) "NEW_LOGO_FLAG"
, COALESCE("MONTH_END"."CONTRACT_REVISION_FLAG", 0) "REVISION_FLAG"
, "MAX"(COALESCE("MONTH_OPEN"."CHURN_MONTH_FLAG", 0)) OVER (PARTITION BY "MONTH_END"."CONTRACTNUM", "MONTH_OPEN"."CUR_MID") "CHURN_MONTH_FLAG"
, "MAX"(COALESCE("MONTH_END"."REVISION_CHANGE_FLAG", 0)) OVER (PARTITION BY "MONTH_END"."CONTRACTNUM", "MONTH_OPEN"."CUR_MID") "REVISION_CHANGE_FLAG"
, "MAX"((CASE WHEN ("MONTH_END"."CONTRACT_MONTH_END" = 1) THEN 1 ELSE 0 END)) OVER (PARTITION BY "MONTH_END"."CONTRACTNUM", "MONTH_OPEN"."CUR_MID") "CONTRACT_ITEM_MONTH_END_FLAG"
, "MAX"("MONTH_END"."MAX_REVISION_BM") OVER (PARTITION BY "MONTH_OPEN"."CONTRACTNUM", "MONTH_OPEN"."CUR_MID") "REVISION_NUMBER_END_MONTH"
, "MONTH_OPEN"."SUB_ACCOUNT"
, "MAX"(COALESCE("MONTH_END"."PARTNER_ACCOUNT_FLAG", 0)) OVER (PARTITION BY "MONTH_OPEN"."CONTRACTNUM", "MONTH_OPEN"."CUR_MID") "PARTNER_ACCOUNT_FLAG"
, COALESCE("MONTH_END"."CLOSE_QTY", 0) "CLOSE_QTY"
, COALESCE("MONTH_OPEN"."CLOSE_QTY", 0) "OPEN_QTY"
, "MONTH_OPEN"."UOM"

FROM
"OPERATIONS_ANALYTICS"."TRANSFORMED_PROD".ES_ERP_MONTH_END_ARR MONTH_END
Right JOIN
"OPERATIONS_ANALYTICS"."TRANSFORMED_PROD".ES_ERP_MONTH_OPEN_ARR MONTH_OPEN
ON ((((("MONTH_END"."PREV_MID" = "MONTH_OPEN"."CUR_MID") AND ("MONTH_END"."CONTRACTNUM" = "MONTH_OPEN"."CONTRACTNUM"))
 AND ("MONTH_END"."ITEM_PROD" = "MONTH_OPEN"."ITEM_PROD")) AND ("MONTH_END"."SUB_ACCOUNT" = "MONTH_OPEN"."SUB_ACCOUNT")) AND ("MONTH_END"."UOM" = "MONTH_OPEN"."UOM"))
 --WHERE MONTH_END.CONTRACTNUM='CT00002217'
);