create or replace view ES_ERP_END_LEFT_JOIN_OPEN(
	CONTRACT_MAKLSYNCDATE,
	UNION_FLAG,
	MONTH_ID,
	CONTRACT_NUM,
	CONTRACT_ID,
	PRODUCT_CLASS,
	ITEM_PROD,
	ITEM_EDITION_ID,
	SALES_AMOUNT,
	DISCOUNT_EXPIRY_ARR,
	PRICE_CHANGE,
	CLOSE_ARR,
	OPEN_ARR,
	NEW_LOGO_FLAG,
	REVISION_FLAG,
	CHURN_MONTH_FLAG,
	REVISION_CHANGE_FLAG,
	CONTRACT_ITEM_MONTH_END_FLAG,
	REVISION_NUMBER_END_MONTH,
	SUB_ACCOUNT,
	PARTNER_ACCOUNT_FLAG,
	CLOSE_QTY,
	OPEN_QTY,
	UOM
) as (

SELECT
   MONTH_END.MAKLSYNCDATE CONTRACT_MAKLSYNCDATE
 , 1 UNION_FLAG
 , MONTH_END.BIMONTHID MONTH_ID
 , MONTH_END.CONTRACTNUM CONTRACT_NUM
 , MONTH_END.CONTRACTID CONTRACT_ID
 , MONTH_END.PRODUCT_CLASS PRODUCT_CLASS
 , MONTH_END.ITEM_PROD ITEM_PROD
 , MONTH_END.USRMAKLEDITIONID ITEM_EDITION_ID
 , (CASE WHEN ((MONTH_END.CLOSE_ARR <> 0) OR (COALESCE(MONTH_OPEN.CLOSE_ARR, 0) <> 0)) THEN MONTH_END.SALES_AMOUNT END) SALES_AMOUNT
 , COALESCE((CASE WHEN ((COALESCE(MONTH_END.CLOSE_ARR, 0) <> 0) OR (COALESCE(MONTH_OPEN.CLOSE_ARR, 0) <> 0)) THEN MONTH_END.DISCOUNT_EXPIRY_ARR END), 0) DISCOUNT_EXPIRY_ARR
 , COALESCE((CASE WHEN ((MONTH_END.CLOSE_ARR <> 0) OR (COALESCE(MONTH_OPEN.CLOSE_ARR, 0) <> 0)) THEN MONTH_END.PRICE_CHANGE END), 0) PRICE_CHANGE
 , MONTH_END.CLOSE_ARR CLOSE_ARR
 , COALESCE((CASE WHEN (MONTH_OPEN.CLOSE_ARR IS NULL) THEN (CASE WHEN (MONTH_END.CONTRACT_NEW_FLAG = 1) THEN 0 WHEN ((MONTH_END.CONTRACT_NEW_WITH_DUP_FLAG = 1) AND (MONTH_END.CONTRACT_NEW_FLAG = 0)) THEN MONTH_END.CLOSE_ARR WHEN (MONTH_END.CONTRACT_REVISION_FLAG = 1) THEN MONTH_END.FIRST_ARR WHEN (MONTH_END.CONTRACT_REVISION_WITH_DUP_FLAG = 1) THEN MONTH_OPEN.CLOSE_ARR ELSE 0 END) ELSE MONTH_OPEN.CLOSE_ARR END), 0) OPEN_ARR
 , MONTH_END.CONTRACT_NEW_FLAG NEW_LOGO_FLAG
 , MONTH_END.CONTRACT_REVISION_FLAG REVISION_FLAG
 , MONTH_END.CHURN_MONTH_FLAG CHURN_MONTH_FLAG
 , MONTH_END.REVISION_CHANGE_FLAG REVISION_CHANGE_FLAG
 , (CASE WHEN (CONTRACT_MONTH_END = 1) THEN 1 ELSE 0 END) CONTRACT_ITEM_MONTH_END_FLAG
 , MAX_REVISION_BM REVISION_NUMBER_END_MONTH
 , MONTH_END.SUB_ACCOUNT
 , (CASE WHEN (COALESCE(MONTH_END.PARTNER_ACCOUNT_FLAG, 0) > 0) THEN 1 ELSE 0 END) PARTNER_ACCOUNT_FLAG
 , MONTH_END.CLOSE_QTY CLOSE_QTY
 , COALESCE((CASE WHEN (MONTH_OPEN.CLOSE_QTY IS NULL) THEN (CASE WHEN (MONTH_END.CONTRACT_NEW_FLAG = 1) THEN 0 WHEN ((MONTH_END.CONTRACT_NEW_WITH_DUP_FLAG = 1) AND (MONTH_END.CONTRACT_NEW_FLAG = 0)) THEN MONTH_END.CLOSE_QTY WHEN (MONTH_END.CONTRACT_REVISION_FLAG = 1) THEN MONTH_END.FIRST_QTY WHEN (MONTH_END.CONTRACT_REVISION_WITH_DUP_FLAG = 1) THEN MONTH_OPEN.CLOSE_QTY ELSE 0 END) ELSE MONTH_OPEN.CLOSE_QTY END), 0) OPEN_QTY
 , MONTH_END.UOM

FROM
OPERATIONS_ANALYTICS.TRANSFORMED_PROD.ES_ERP_MONTH_END_ARR MONTH_END
LEFT JOIN
OPERATIONS_ANALYTICS.TRANSFORMED_PROD.ES_ERP_MONTH_OPEN_ARR MONTH_OPEN
ON (((((MONTH_END.PREV_MID = MONTH_OPEN.CUR_MID) AND (MONTH_END.CONTRACTNUM = MONTH_OPEN.CONTRACTNUM))
 AND (MONTH_END.ITEM_PROD = MONTH_OPEN.ITEM_PROD)) AND (MONTH_END.SUB_ACCOUNT = MONTH_OPEN.SUB_ACCOUNT)) AND (MONTH_END.UOM = MONTH_OPEN.UOM))
 --WHERE MONTH_END.CONTRACTNUM='CT00002217'


  );