create or replace TABLE ES_ERP_MONTH_OPEN_ARR_TABLE (
	CONTRACTNUM VARCHAR(16777216),
	BIMONTHID NUMBER(8,0),
	CONTRACTID NUMBER(38,0),
	ITEM_PROD VARCHAR(16777216),
	SALES_AMOUNT FLOAT,
	PRICE_CHANGE FLOAT,
	CLOSE_ARR FLOAT,
	SUB_ACCOUNT NUMBER(38,0),
	CLOSE_QTY FLOAT,
	UOM VARCHAR(16777216),
	MAKLSYNCDATE TIMESTAMP_NTZ(9),
	CHURN_MONTH_FLAG NUMBER(1,0),
	PRODUCT_CLASS VARCHAR(16777216),
	USRMAKLEDITIONID NUMBER(38,0),
	CUR_MID DATE,
	PREV_MID DATE,
	NEXT_MID DATE
);