create or replace view ES_ERP_CONTRACT_BY_PRODUCT_WITH_PRICE_CHANGE_ADJUSTMENT(
	PROD_EDITION,
	PROD_ITEM_EDITION,
	CUSTOMERID,
	REVISIONNBR,
	REV_COMMENTS,
	REV_AUTOGEN_ID,
	IMPORT_FLAG,
	PARTNER_SWITCH_FLAG,
	REGION,
	PROJECT,
	PARTNER,
	NO_EMPLOYEE,
	CLIENT_ID,
	ACCOUNT_NAME,
	ARCHIE_CLIENT_ID,
	INDUSTRY,
	SUB_INDUSTRY,
	CONTRACT_START_DT,
	CONTRACT_CANCEL_DATE,
	CONTRACT_CANCEL_CODE,
	COUNTRY,
	PRODUCTCLASS,
	NEXT_CHARGE_DATE,
	CONTRACT_MAKLSYNCDATE,
	UNION_FLAG,
	MONTH_ID,
	CONTRACT_NUM,
	CONTRACT_ID,
	PRODUCT_CLASS,
	ITEM_PROD,
	ITEM_EDITION_ID,
	SALES_AMOUNT,
	DISCOUNT_EXPIRY_ARR,
	PRICE_CHANGE,
	PRICE_CHANGE_AJUSTMENT,
	PRICE_CHANGE_AJUSTED,
	CLOSE_ARR,
	OPEN_ARR,
	NEW_LOGO_FLAG,
	REVISION_FLAG,
	CHURN_MONTH_FLAG,
	REVISION_CHANGE_FLAG,
	CONTRACT_ITEM_MONTH_END_FLAG,
	REVISION_NUMBER_END_MONTH,
	SUB_ACCOUNT,
	PARTNER_ACCOUNT_FLAG,
	CLOSE_QTY,
	OPEN_QTY,
	UOM,
	ROW_UNION_FLAG,
	ITEM_EDITION_DESCRIPTION,
	ITEM_EDITION_SHORT,
	MAX_GENDATE,
	MAX_GENMONTH,
	CHURN_MONTH_ID,
	PARTNER_SWITCH_PRICE_CHANGE_FLAG,
	PARTNER_SWITCH_MONTH_ID,
	PARTNER_SWITCH_CONTRACT
) as
    

SELECT 
PROD_EDITION, 
PROD_ITEM_EDITION, 
CUSTOMERID, 
REVISIONNBR, 
REV_COMMENTS, 
REV_AUTOGEN_ID, 
IMPORT_FLAG, 
PARTNER_SWITCH_FLAG, 
REGION, 
PROJECT, 
PARTNER, 
NO_EMPLOYEE, 
CLIENT_ID, 
ACCOUNT_NAME, 
ARCHIE_CLIENT_ID, 
INDUSTRY, 
SUB_INDUSTRY, 
CONTRACT_START_DT, 
CONTRACT_CANCEL_DATE, 
CONTRACT_CANCEL_CODE, 
COUNTRY, 
PRODUCTCLASS, 
NEXT_CHARGE_DATE, 
CONTRACT_MAKLSYNCDATE, 
UNION_FLAG,
MONTH_ID, 
CONTRACT_NUM,
CONTRACT_ID, 
PRODUCT_CLASS, 
ITEM_PROD, 
ITEM_EDITION_ID, 
SALES_AMOUNT, 
DISCOUNT_EXPIRY_ARR, 
PRICE_CHANGE, 
PRICE_CHANGE_AMOUNT AS PRICE_CHANGE_AJUSTMENT, 
CASE WHEN PARTNER_SWITCH_PRICE_CHANGE_FLAG = 1 THEN PRICE_CHANGE_AMOUNT ELSE PRICE_CHANGE END AS PRICE_CHANGE_AJUSTED,
CLOSE_ARR, 
OPEN_ARR, 
NEW_LOGO_FLAG, 
REVISION_FLAG, 
CHURN_MONTH_FLAG, 
REVISION_CHANGE_FLAG, 
CONTRACT_ITEM_MONTH_END_FLAG, 
REVISION_NUMBER_END_MONTH, 
SUB_ACCOUNT, 
PARTNER_ACCOUNT_FLAG, 
CLOSE_QTY, 
OPEN_QTY, 
UOM,
ROW_UNION_FLAG, 
ITEM_EDITION_DESCRIPTION, 
ITEM_EDITION_SHORT,
MAX_GENDATE, 
MAX_GENMONTH, 
CHURN_MONTH_ID, 
PARTNER_SWITCH_PRICE_CHANGE_FLAG,
PARTNER_SWITCH_MONTH_ID,PARTNER_SWITCH_CONTRACT FROM

(

WITH CTEA AS (

SELECT * ,
MAX(CASE WHEN CHURN_MONTH_ID = PARTNER_SWITCH_MONTH_ID THEN CONTRACT_ID ELSE 0 END) over (partition by contract_num)  AS PARTNER_SWITCH_CONTRACT FROM
(select *, 
max(case when PARTNER_SWITCH_FLAG = 1 then MONTH_ID else 0 end) over (partition by contract_num) as PARTNER_SWITCH_MONTH_ID
--,(CASE WHEN CHURN_MONTH_ID IS NOT NULL then CONTRACT_ID ELSE 0 END) as older_contract
 , CASE WHEN PARTNER_SWITCH_FLAG = 1 and to_char(NEXT_CHARGE_DATE,'YYYYMM') > MONTH_ID THEN 1 ELSE 0 END AS PARTNER_SWITCH_PRICE_CHANGE_FLAG
from OPERATIONS_ANALYTICS.TRANSFORMED_PROD.ES_ERP_CONTRACT_BY_PRODUCT 
 --where client_id = 'BA00006812' 
 --and 
 --item_prod ='Maintenance Approvals' and 
 --month_id ='202202' 
 order by month_id desc)


),

CTEB AS
 (
select 
 to_char(MAKLSYNCDATE,'YYYYMM') AS MONTH_ID_PHOENIX, CONTRACTID, inventoryid,descr, MAX(PRICECHANGEANNUALISEDAMT) AS PRICE_CHANGE_AMOUNT
  FROM
(WITH CTE1 as
(select * from PURCHASING.PUBLISHED_PROD.PHOENIX_MAKLXRBANNUALISEDVALUE 
 --where CONTRACTID IN ('5889', '8310')
),

CTE2 as
(select INVENTORYID AS INVENTORYID_INVENTORY, MAKLSYNCDATE as MAKLSYNCDATE_INVENTORY, DESCR from PURCHASING.PUBLISHED_PROD.PHOENIX_INVENTORYITEM)

select * from CTE1 left join CTE2 on CTE1.MAKLSYNCDATE = CTE2.MAKLSYNCDATE_INVENTORY and CTE1.INVENTORYID = CTE2.INVENTORYID_INVENTORY) 
     --where MAKLSYNCDATE like '2022-02%' 
    --and 
    --DESCR = 'Maintenance Approvals' 
    group by 1,2,3,4
    )

 
SELECT * FROM CTEA LEFT JOIN CTEB ON CTEA.PARTNER_SWITCH_MONTH_ID = CTEB.MONTH_ID_PHOENIX AND CTEA.PARTNER_SWITCH_CONTRACT = CTEB.CONTRACTID AND CTEA.ITEM_PROD = CTEB.DESCR)
--WHERE client_id = 'BA00006473' 
--group by PROD_EDITION, PROD_ITEM_EDITION, CUSTOMERID, REVISIONNBR, REV_COMMENTS, REV_AUTOGEN_ID, IMPORT_FLAG, PARTNER_SWITCH_FLAG, REGION, PROJECT, PARTNER, NO_EMPLOYEE, CLIENT_ID, ACCOUNT_NAME, ARCHIE_CLIENT_ID, INDUSTRY, SUB_INDUSTRY, CONTRACT_START_DT, CONTRACT_CANCEL_DATE, CONTRACT_CANCEL_CODE, COUNTRY, PRODUCTCLASS, NEXT_CHARGE_DATE, CONTRACT_MAKLSYNCDATE, UNION_FLAG, MONTH_ID, CONTRACT_NUM, CONTRACT_ID, PRODUCT_CLASS, ITEM_PROD, ITEM_EDITION_ID, SALES_AMOUNT, DISCOUNT_EXPIRY_ARR, PRICE_CHANGE, CLOSE_ARR, OPEN_ARR, NEW_LOGO_FLAG, REVISION_FLAG, CHURN_MONTH_FLAG, REVISION_CHANGE_FLAG, CONTRACT_ITEM_MONTH_END_FLAG, REVISION_NUMBER_END_MONTH, SUB_ACCOUNT, PARTNER_ACCOUNT_FLAG, CLOSE_QTY, OPEN_QTY, UOM, ROW_UNION_FLAG, ITEM_EDITION_DESCRIPTION, ITEM_EDITION_SHORT, MAX_GENDATE, MAX_GENMONTH, CHURN_MONTH_ID, PARTNER_SWITCH_PRICE_CHANGE_FLAG,PARTNER_SWITCH_MONTH_ID,PARTNER_SWITCH_CONTRACT,MONTH_ID_PHOENIX,CONTRACTID, inventoryid,descr
ORDER BY MONTH_ID DESC;