create or replace TABLE ES_ERP_PAYROLL_ARR_AND_MOVEMENT_SUMMARY_BY_MOVEMENT_TYPE (
	MONTH_ID NUMBER(38,0),
	ARR_NEW_ADDS FLOAT,
	ARR_NEW_EXPANSION FLOAT,
	ARR_MIGRATION_ADDS FLOAT,
	ARR_DISCOUNT_EXPIRED FLOAT,
	ARR_NEW_PRICE_CHANGE FLOAT,
	ARR_CHURNED FLOAT,
	ARR_DOWNGRADE FLOAT
);