create or replace view ES_ERP_CONTRACT_BY_PRODUCT_ITEM_EDITION_WITH_PRICE_CHANGE_ADJUSTMENT(
	MONTH_ID,
	PRODUCT_SEGMENT,
	CUSTOMER_ID,
	ARCHIE_CLIENT_ID,
	CONTRACT_NUM,
	CONTRACT_ID,
	PRODUCT_CLASS,
	PROD_EDITION,
	PROD_ITEM_EDITION,
	ITEM_EDITION_DESCRIPTION,
	ITEM_EDITION_SHORT,
	OPEN_ARR,
	CLOSE_ARR,
	NET_ARR_CHANGE,
	ARR_NEW_ADDS,
	ARR_MIGRATION_ADDS,
	ARR_CANCELLED,
	ARR_PRICE_CHANGE,
	ARR_DISCOUNT_EXPIRED,
	ARR_EXPANSION,
	ARR_DOWNGRADE,
	ARR_OTHER_CHANGE,
	ARR_IMPORT,
	REGION,
	PROJECT,
	PARTNER,
	CLIENT_ID,
	ACCOUNT_NAME,
	NO_EMPLOYEE,
	INDUSTRY,
	SUB_INDUSTRY,
	CONTRACT_START_DT,
	COUNTRY,
	PRODUCTCLASS,
	NO_ARR_FLAG,
	CONTRACT_MAKLSYNCDATE,
	NEW_LOGO_FLAG,
	SUB_ACCOUNT,
	PARTNER_ACCOUNT_FLAG,
	MAX_GENDATE,
	MAX_GENMONTH,
	CHURN_MONTH_ID,
	REVISION_NUMBER_END_MONTH,
	REVISIONNBR,
	REV_COMMENTS,
	REV_AUTOGEN_ID,
	IMPORT_FLAG,
	PARTNER_SWITCH_FLAG,
	CONTRACT_CANCEL_DATE,
	CONTRACT_CANCEL_CODE,
	NEXT_CHARGE_DATE,
	ARCHIE_AGREE_NUM,
	ARCHIE_ASSET_NUM,
	INSERT_DATE,
	MIG_FLAG,
	MIG_TO,
	MIG_FROM,
	MIGRATION_PRACTICE,
	OPEN_EE_COUNT,
	CLOSE_EE_COUNT,
	AGREE_STATUS,
	FSWD_FLAG
) as

with prod_item_edition as (

SELECT

MONTH_ID
,CASE WHEN PROD_EDITION='EXO Employer Services' then 'Enterprise Payroll' else 'ENT ERP' end As PRODUCT_SEGMENT
,CLIENT_ID AS CUSTOMER_ID
,ARCHIE_CLIENT_ID
,CONTRACT_NUM
,CONTRACT_ID
,PRODUCT_CLASS
--,ENTERPRISE_CATEGORY
,PROD_EDITION
,PROD_ITEM_EDITION
,Item_Edition_Description AS ITEM_EDITION_DESCRIPTION
,ITEM_EDITION_SHORT
,OPEN_ARR
,CLOSE_ARR
,NET_ARR_CHANGE
,CASE WHEN IMPORT_FLAG=1 then 0 WHEN MIG_OPPS.MIG_OPP_FLAG=1 THEN 0  ELSE ARR_NEW_ADDS END ARR_NEW_ADDS
,CASE WHEN IMPORT_FLAG=1 then 0 WHEN MIG_OPPS.MIG_OPP_FLAG=1 THEN ARR_NEW_ADDS ELSE 0 END ARR_MIGRATION_ADDS
,ARR_CANCELLED
--,ARR_PRICE_CHANGE
,CASE WHEN SUM(ARR_PRICE_CHANGE) OVER (PARTITION BY MONTH_ID,CONTRACT_NUM,PROD_ITEM_EDITION)>=0 then ARR_PRICE_CHANGE else 0 end as ARR_PRICE_CHANGE
,ARR_DISCOUNT_EXPIRED
,CASE --WHEN PARTNER_SWITCH_PRICE_CHANGE_FLAG = 1 THEN 0
      WHEN IMPORT_FLAG=1 then 0
      WHEN SUM(ARR_OTHER_CHANGE) OVER (PARTITION BY MONTH_ID,CONTRACT_NUM)>0 THEN ARR_OTHER_CHANGE ELSE 0 END AS ARR_EXPANSION
,CASE WHEN IMPORT_FLAG=1 then 0
      WHEN SUM(ARR_OTHER_CHANGE) OVER (PARTITION BY MONTH_ID,CONTRACT_NUM)<0 THEN ARR_OTHER_CHANGE
      ELSE 0 END +
       CASE WHEN IMPORT_FLAG=1 then 0
      WHEN SUM(ARR_PRICE_CHANGE) OVER (PARTITION BY MONTH_ID,CONTRACT_NUM,PROD_ITEM_EDITION)<0 then ARR_PRICE_CHANGE
      ELSE 0 END
       AS ARR_DOWNGRADE
,CASE WHEN IMPORT_FLAG=1 then 0
      WHEN SUM(ARR_OTHER_CHANGE) OVER (PARTITION BY MONTH_ID,CONTRACT_NUM)=0 THEN ARR_OTHER_CHANGE ELSE 0 END AS ARR_OTHER_CHANGE
,CASE WHEN IMPORT_FLAG=1 then ARR_OTHER_CHANGE ELSE 0 END AS ARR_IMPORT
--,ARR_OTHER_CHANGE
,REGION
,PROJECT
,PARTNER 
,CLIENT_ID
,ACCOUNT_NAME
,NO_EMPLOYEE
,INDUSTRY
,SUB_INDUSTRY
,CONTRACT_START_DT
,COUNTRY
,PRODUCTCLASS
,CASE WHEN CLOSE_ARR=0 AND OPEN_ARR=0 THEN 1 ELSE 0 END AS NO_ARR_FLAG
,CONTRACT_MAKLSYNCDATE
,NEW_LOGO_FLAG
--,REVISION_FLAG
--,REVISION_CHANGE_FLAG
,SUB_ACCOUNT
,PARTNER_ACCOUNT_FLAG
,MAX_GENDATE
,MAX_GENMONTH
,CHURN_MONTH_ID
,REVISION_NUMBER_END_MONTH
,REVISIONNBR
,REV_COMMENTS
,REV_AUTOGEN_ID
,CASE WHEN IMPORT_FLAG=1 THEN 1 ELSE 0 END  AS IMPORT_FLAG
,CASE WHEN PARTNER_SWITCH_FLAG=1 THEN 1 ELSE 0 END AS PARTNER_SWITCH_FLAG
,CONTRACT_CANCEL_DATE
,CONTRACT_CANCEL_CODE
,NEXT_CHARGE_DATE
,CASE WHEN MIG_OPPS.MIG_OPP_FLAG=1 THEN 1 ELSE 0 END AS MIG_FLAG
,MIG_OPPS.usrinteddescr AS MIG_TO
,MIG_OPPS.usrmaklmigratedfrom AS MIG_FROM
,case when MAX(MIG_OPPS.MIG_OPP_FLAG) OVER (PARTITION BY CLIENT_ID) >0 then 'Y' ELSE 'N' END AS MIGRATION_PRACTICE
FROM (


SELECT
MONTH_ID
,CLIENT_ID AS CUSTOMER_ID
,CONTRACT_NUM
,CONTRACT_ID
,PRODUCT_CLASS
--,ENTERPRISE_CATEGORY
,PROD_EDITION
,PROD_ITEM_EDITION
,Item_Edition_Description
--,ITEM_PROD
--,ITEM_EDITION_ID
,SUM(OPEN_ARR) AS OPEN_ARR
,SUM(CLOSE_ARR) AS CLOSE_ARR
,SUM(CLOSE_ARR - OPEN_ARR) AS NET_ARR_CHANGE
,CASE WHEN NEW_LOGO_FLAG=1 THEN SUM(CLOSE_ARR - OPEN_ARR) ELSE 0 END AS  ARR_NEW_ADDS
,CASE WHEN REVISIONNBR <REVISION_NUMBER_END_MONTH_1  AND CHURN_MONTH_ID=MONTH_ID THEN 0
      WHEN CHURN_MONTH_ID=MONTH_ID THEN SUM(CLOSE_ARR  - OPEN_ARR)
      ELSE 0  END AS ARR_CANCELLED
--CHURN_MONTH_FLAG=1
,   CASE --WHEN PARTNER_SWITCH_PRICE_CHANGE_FLAG = 1 THEN SUM(PRICE_CHANGE_AJUSTMENT)
         WHEN NEW_LOGO_FLAG=0 AND (CHURN_MONTH_ID<>MONTH_ID OR CHURN_MONTH_ID IS NULL) THEN ROUND(SUM(coalesce(PRICE_CHANGE_AJUSTED,0)),2) ELSE 0 END AS ARR_PRICE_CHANGE
,CASE WHEN NEW_LOGO_FLAG=0 AND (CHURN_MONTH_ID<>MONTH_ID OR CHURN_MONTH_ID IS NULL) THEN ROUND(SUM(DISCOUNT_EXPIRY_ARR),2) ELSE 0 END AS ARR_DISCOUNT_EXPIRED
-- ,CASE WHEN NEW_LOGO_FLAG=0 AND (CHURN_MONTH_ID<>MONTH_ID OR CHURN_MONTH_ID IS NULL) AND ROUND(SUM(SALES_AMOUNT - DISCOUNT_EXPIRY_ARR),0)>0 THEN SUM(SALES_AMOUNT - DISCOUNT_EXPIRY_ARR) ELSE 0 END AS ARR_EXPANSION
-- ,CASE WHEN NEW_LOGO_FLAG=0 AND (CHURN_MONTH_ID<>MONTH_ID OR CHURN_MONTH_ID IS NULL) AND ROUND(SUM(SALES_AMOUNT - DISCOUNT_EXPIRY_ARR),0)<0 THEN SUM(SALES_AMOUNT - DISCOUNT_EXPIRY_ARR) ELSE 0 END AS ARR_DOWNGRADE

,CASE WHEN NEW_LOGO_FLAG=0 AND (CHURN_MONTH_ID<>MONTH_ID OR CHURN_MONTH_ID IS NULL) THEN SUM(CLOSE_ARR - OPEN_ARR - coalesce(PRICE_CHANGE_AJUSTED,0) - ROUND(DISCOUNT_EXPIRY_ARR,2))
      WHEN REVISIONNBR <REVISION_NUMBER_END_MONTH_1  AND CHURN_MONTH_ID=MONTH_ID THEN SUM(CLOSE_ARR  - OPEN_ARR) ELSE 0 END AS ARR_OTHER_CHANGE
,REGION
,PROJECT
,PARTNER
,NO_EMPLOYEE
,INDUSTRY
,SUB_INDUSTRY
,CONTRACT_START_DT
,COUNTRY
,PRODUCTCLASS
,CONTRACT_MAKLSYNCDATE
,NEW_LOGO_FLAG
,REVISION_FLAG
,REVISION_CHANGE_FLAG
,REVISION_NUMBER_END_MONTH_1  as REVISION_NUMBER_END_MONTH
,SUB_ACCOUNT
,PARTNER_ACCOUNT_FLAG
,ITEM_EDITION_SHORT
,MAX_GENDATE
,MAX_GENMONTH
,CHURN_MONTH_ID
,REVISIONNBR
,REV_COMMENTS
,REV_AUTOGEN_ID
,IMPORT_FLAG
,PARTNER_SWITCH_FLAG
,CONTRACT_CANCEL_DATE
,CONTRACT_CANCEL_CODE
,NEXT_CHARGE_DATE
,CLIENT_ID
,ACCOUNT_NAME
,ARCHIE_CLIENT_ID
,PARTNER_SWITCH_PRICE_CHANGE_FLAG
 FROM (
SELECT
    *,MAX(coalesce(cast(REVISION_NUMBER_END_MONTH as integer),0)) OVER (PARTITION BY CONTRACT_NUM,MONTH_ID) AS REVISION_NUMBER_END_MONTH_1
     FROM (
     OPERATIONS_ANALYTICS.TRANSFORMED_PROD.ES_ERP_CONTRACT_BY_PRODUCT_WITH_PRICE_CHANGE_ADJUSTMENT--es_contract_line_by_contract_item_monthly_view
    --
        ) EDITION
--
--     WHERE
--      1=1
-- AND MONTH_ID=202103-- IN (202101,202102,202103)--->=202008--IN (202011,202012,202101,202102,202103)
-- AND CONTRACT_NUM ='CT00005922'--'CT00005431'--'CT00003514'--in ('CT00004849','CT00004886')
--='CT00001245'--'CT00000002'--'CT00005389'--'CT00005389'--'CT00004820'--'CT00003690'--'CT00003690'--'CT00004323'
--AND MONTH_ID =202101
--AND MAX_GENDATE
--and (MAX_GENDATE<>MONTH_ID OR churn_month_id=MONTH_ID)


) ITEM_DESCRIPTION_LEVEL

GROUP BY
PROD_EDITION
,PROD_ITEM_EDITION
,REGION
,PROJECT
,PARTNER
,NO_EMPLOYEE
,INDUSTRY
,SUB_INDUSTRY
,CONTRACT_START_DT
,COUNTRY
,PRODUCTCLASS
,CONTRACT_MAKLSYNCDATE
,MONTH_ID
,CONTRACT_NUM
,CONTRACT_ID
,PRODUCT_CLASS
,NEW_LOGO_FLAG
,REVISION_FLAG
,REVISION_CHANGE_FLAG
,REVISION_NUMBER_END_MONTH_1
,SUB_ACCOUNT
,PARTNER_ACCOUNT_FLAG
,ITEM_EDITION_DESCRIPTION
,ITEM_EDITION_SHORT
,MAX_GENDATE
,MAX_GENMONTH
,CHURN_MONTH_ID
,customerid
,REVISIONNBR
,REV_COMMENTS
,REV_AUTOGEN_ID
,IMPORT_FLAG
,PARTNER_SWITCH_FLAG
,CONTRACT_CANCEL_DATE
,CONTRACT_CANCEL_CODE
,NEXT_CHARGE_DATE
,CLIENT_ID
,ACCOUNT_NAME
,ARCHIE_CLIENT_ID
,PARTNER_SWITCH_PRICE_CHANGE_FLAG
) GET_ARR_CATEGORY

LEFT JOIN

(
SELECT
opp.opportunityid
,opp.closingdate
,opp.subject
,opp.usrmaklmigratedfrom
,opp.usrmaklopportunitysubtype
,opp.stageid
,opp.status
,opp.usrmakltype
,edi.usrinteddescr
,1 AS MIG_OPP_FLAG
 FROM PURCHASING.PUBLISHED_PROD.PHOENIX_CROPPORTUNITY opp
left join (select * from PURCHASING.PUBLISHED_PROD.PHOENIX_MAKLEDITION where maklsyncdate
=(select Max(maklsyncdate) from PURCHASING.PUBLISHED_PROD.PHOENIX_MAKLEDITION)) edi on opp.usrmakleditionid=edi.editionid
 where opp.maklsyncdate = (select max(maklsyncdate) from PURCHASING.PUBLISHED_PROD.PHOENIX_CROPPORTUNITY)
 and opp.status='W'
 and (opp.usrmaklopportunitysubtype='Migrated Site' or UPPER(opp.subject) like '%MIGRAT%'))
 MIG_OPPS
ON trim(substr(GET_ARR_CATEGORY.REV_COMMENTS,position('PP'in GET_ARR_CATEGORY.REV_COMMENTS)))=MIG_OPPS.opportunityid
--
-- WHERE Contract_Num='CT00005972'
--
-- where CONTRACT_NUM ='CT00000834'--'CT00005922'--'CT00005431'--'CT00003514'--in ('CT00004849','CT00004886')
-- AND MONTH_ID=202101

--where --CONTRACT_NUM ='CT00006210' AND--'CT00005946'--'CT00005988'--'CT00005979'--'CT00000834'--'CT00005922'--'CT00005431'--'CT00003514'--in ('CT00004849','CT00004886')
--      MONTH_ID=202107
),
FSWD as (
 SELECT DISTINCT
    ACC.CLIENT_ID
    --UPPER(OPTY.NAME) AS OPTY_NAME_UPPER
  FROM CRM.TRANSFORMED_PROD.OPPORTUNITY AS OPTY
  LEFT JOIN CRM.TRANSFORMED_PROD.ACCOUNT AS ACC ON ACC.ACCOUNT_ID = OPTY.ACCOUNTID
  WHERE UPPER(OPTY.NAME) LIKE '%FSWD%'
)
    
    select 
month_id
,product_segment
,customer_id
,archie_client_id
,contract_num
,contract_id
,product_class
,prod_edition
,prod_item_edition
,item_edition_description
,item_edition_short
,open_arr
,close_arr
,net_arr_change
,arr_new_adds
,arr_migration_adds
,arr_cancelled
,arr_price_change
,arr_discount_expired
,arr_expansion
,arr_downgrade
,arr_other_change
,arr_import
,region
,project
,partner
,pie.client_id
,account_name
,no_employee
,industry
,sub_industry
,contract_start_dt
,country
,productclass
,no_arr_flag
,contract_maklsyncdate
,new_logo_flag
,sub_account
,partner_account_flag
,max_gendate
,max_genmonth
,churn_month_id
,revision_number_end_month
,revisionnbr
,rev_comments
,rev_autogen_id
,import_flag
,partner_switch_flag
,contract_cancel_date
,contract_cancel_code
,next_charge_date
,null as archie_agree_num
,null as archie_asset_num
,null as INSERT_DATE
,mig_flag
,mig_to
,mig_from
,migration_practice
,null as open_ee_count
,null as close_ee_count
,null as agree_status
--,PARTNER_SWITCH_PRICE_CHANGE_FLAG,
,case when f.CLIENT_ID is null then 'N' else 'Y' end as FSWD_FLAG
    from 
    prod_item_edition pie
    LEFT JOIN FSWD f ON pie.ARCHIE_CLIENT_ID = f.CLIENT_ID;