create or replace TABLE ES_ERP_PAYROLL_ARR_AND_MOVEMENT_SUMMARY_BY_PRODUCT_GROUP (
	MONTH_ID NUMBER(38,0),
	PRODUCT_GROUP VARCHAR(16777216),
	CLOSE_ARR FLOAT,
	COUNT_CONTRACTS NUMBER(18,0),
	COUNT_CUSTOMERS NUMBER(18,0)
);