create or replace view ES_OPPORTUNITY_VIEW(
	COUNTRY,
	OPP_SOURCE,
	PRODUCT,
	REGION,
	STAGE_NAME,
	SALES_VALUE,
	PROJECT_ID,
	PARTNER,
	CLOSED_DATE,
	CREATED_DATE,
	OPP_ID,
	USRMAKLTYPE,
	STATUS,
	CLOSEDATE,
	USRMAKLINCLUDEIN,
	NOTEID,
	OWNERID,
	INDUSTRY,
	SUB_INDUSTRY,
	CONTRACTID,
	CONTRACTLINENBR,
	QUOTENBR
) as
SELECT
  "BRANCH"."COUNTRYID" "COUNTRY"
, (CASE "OPP"."USRMAKLOPPORTUNITYSOURCE" WHEN 'M' THEN 'MYOB' WHEN 'P' THEN 'PARTNER' END) "OPP_SOURCE"
, (CASE "OPP"."CLASSID" WHEN 'ADV' THEN 'ADVANCED' WHEN 'EXO' THEN 'EXO' WHEN 'GTR' THEN 'GREENTREE' END) "PRODUCT"
, (CASE "OPP"."USRMAKLSALESREGIONID" WHEN 'AUEST' THEN 'EAST' WHEN 'AUNTH' THEN 'NORTH' WHEN 'AUSTH' THEN 'SOUTH' ELSE "OPP"."USRMAKLSALESREGIONID" END) "REGION"
, "PROB"."NAME" "STAGE_NAME"
, "OPP"."USRMAKLCURYSALESAMT" "SALES_VALUE"
, "PROJECT"."DESCRIPTION" "PROJECT_ID"
, "PARTNER"."ACCTNAME" "PARTNER"
, "OPP"."CLOSINGDATE" "CLOSED_DATE"
, "OPP"."CREATEDDATETIME" "CREATED_DATE"
, "OPP"."OPPORTUNITYID" "OPP_ID"
, "OPP"."USRMAKLTYPE"
, "OPP"."STATUS"
, "OPP"."CLOSEDATE"
, "OPP"."USRMAKLINCLUDEIN"
, "OPP"."NOTEID"
, "OPP"."OWNERID"
, "INDUSTRY"."INDUSTRY"
, "SUB_INDUSTRY"."SUB_INDUSTRY"
, "CONTRACT_LINE"."CONTRACTID"
, "CONTRACT_LINE"."LINENBR" "CONTRACTLINENBR"
, "CONTRACT_LINE"."USRMAKLQUOTENBR" "QUOTENBR"
FROM
  ((((((((((((
   SELECT *
   FROM
     PURCHASING.RAW.CROPPORTUNITY
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.CROPPORTUNITY
))
)  OPP
LEFT JOIN (
   SELECT *
   FROM
     PURCHASING.RAW.BACCOUNT
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.BACCOUNT
))
)  ACC ON ("OPP"."BACCOUNTID" = "ACC"."BACCOUNTID"))
LEFT JOIN (
   SELECT *
   FROM
     PURCHASING.RAW.BRANCH
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.BRANCH
))
)  BRANCH ON ("OPP"."BRANCHID" = "BRANCH"."BRANCHID"))
LEFT JOIN (
   SELECT *
   FROM
     PURCHASING.RAW.CROPPORTUNITYPROBABILITY
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.CROPPORTUNITYPROBABILITY
))
)  PROB ON ("OPP"."STAGEID" = "PROB"."STAGECODE"))
LEFT JOIN (
   SELECT *
   FROM
     PURCHASING.RAW.MAKLSALESREGION
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.MAKLSALESREGION
))
)  REGION ON ("OPP"."USRMAKLSALESREGIONID" = "REGION"."SALESREGIONID"))
LEFT JOIN (
   SELECT *
   FROM
     PURCHASING.RAW.USERS
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.USERS
))
)  MYOBOWNER ON ("OPP"."OWNERID" = "MYOBOWNER"."PKID"))
LEFT JOIN (
   SELECT *
   FROM
     PURCHASING.RAW.PMPROJECT
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.PMPROJECT
))
)  PROJECT ON ("OPP"."PROJECTID" = "PROJECT"."CONTRACTID"))
LEFT JOIN (
   SELECT *
   FROM
     PURCHASING.RAW.VENDOR
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.VENDOR
))
)  PARTNER ON ("PROJECT"."CUSTOMERID" = "PARTNER"."BACCOUNTID"))
LEFT JOIN (
   SELECT "BACCOUNTID"
   FROM
     PURCHASING.RAW.VENDOR
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.VENDOR
))
)  PARTNER_FLG ON ("OPP"."BACCOUNTID" = "PARTNER_FLG"."BACCOUNTID"))
LEFT JOIN (
   SELECT
     "INDUSTRYID"
   , "DESCR" "INDUSTRY"
   FROM
     PURCHASING.RAW.MAKLINDUSTRY
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.MAKLINDUSTRY
))
)  INDUSTRY ON ("ACC"."USRMAKLINDUSTRY" = "INDUSTRY"."INDUSTRYID"))
LEFT JOIN (
   SELECT
     "SUBINDUSTRYID"
   , "DESCR" "SUB_INDUSTRY"
   FROM
     PURCHASING.RAW.MAKLSUBINDUSTRY
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.MAKLINDUSTRY
))
)  SUB_INDUSTRY ON ("ACC"."USRMAKLSUBINDUSTRY" = "SUB_INDUSTRY"."SUBINDUSTRYID"))
LEFT JOIN (
   SELECT
     "REPLACE"("COMMENTS", 'UPSELL - ', '') "OPP_ID"
   , "CONTRACTID"
   , "LINENBR"
   , "USRMAKLQUOTENBR"
   FROM
     PURCHASING.RAW.MAKLXRBCONTRDETPREVNEXT
   WHERE ("MAKLSYNCDATE" = (SELECT "MAX"("MAKLSYNCDATE")
FROM
  PURCHASING.RAW.MAKLXRBCONTRDETPREVNEXT
))
)  CONTRACT_LINE ON ("OPP"."OPPORTUNITYID" = "CONTRACT_LINE"."OPP_ID"))
WHERE ("PARTNER_FLG"."BACCOUNTID" IS NULL);