create or replace view STRIPE_PRICES_PRODUCTS(
	PRICE_ID,
	PRODUCT_ID,
	PRICE_CURRENCY,
	PRICE_NICKNAME,
	PRICE_RECURRING_INTERVAL,
	PRICE_RECURRING_INTERVAL_COUNT,
	PRICE_UNIT_AMOUNT_DECIMAL,
	PRODUCT_NAME,
	POSTING_CLASS,
	POSTING_TYPE,
	PRODUCT_CODE,
	SALES_ACCOUNT,
	ITEM_CLASS,
	PRICE_PROTECTION_PERIODS,
	MIN_QUANTITY,
	MAX_QUANTITY,
	EXTERNAL_REFERENCE,
	PRICE_COMPANY_SIZE_BUCKET,
	PRICE_MYOB_ADVANCED_EDITION,
	PRICE_INVENTORY_ID,
	PRICE_EFFECTIVE_YEAR
) as (
     

/*
    Purpose:             Make it easier to report on prices and product data
    Created Date:        202402
    Description:         Creates a  view of stripe prices and products including metadata
  */

select 

    --STRIPE_PRICES.BILLING_SCHEME AS PRICE_BILLING_SCHEME,

    STRIPE_PRICES.PRICE_ID,
    STRIPE_PRICES.product_id,
    STRIPE_PRICES.CURRENCY AS PRICE_CURRENCY,
    STRIPE_PRICES.NICKNAME AS PRICE_NICKNAME,
    STRIPE_PRICES.RECURRING_INTERVAL AS PRICE_RECURRING_INTERVAL,
    STRIPE_PRICES.RECURRING_INTERVAL_COUNT AS PRICE_RECURRING_INTERVAL_COUNT,
    --STRIPE_PRICES.TYPE AS PRICE_TYPE,
    round(case when STRIPE_PRICES.UNIT_AMOUNT_DECIMAL > 0 
         then STRIPE_PRICES.UNIT_AMOUNT_DECIMAL / 100
         else STRIPE_PRICES.UNIT_AMOUNT_DECIMAL end ,2) 
         AS PRICE_UNIT_AMOUNT_DECIMAL,
    STRIPE_PRODUCTS.NAME AS PRODUCT_NAME,
    PRODUCTS_METADATA_POSTING_CLASS.VALUE AS POSTING_CLASS,
    PRODUCTS_METADATA_PRODUCT_TYPE.VALUE AS POSTING_TYPE,
    PRODUCTS_METADATA_PRODUCT_CODE.VALUE AS PRODUCT_CODE,
    PRODUCTS_METADATA_SALES_ACCOUNT.VALUE AS SALES_ACCOUNT,
    PRODUCTS_METADATA_ITEM_CLASS.VALUE AS ITEM_CLASS,
    PRODUCTS_METADATA_PRICE_PROTECTION_PERIODS.VALUE as PRICE_PROTECTION_PERIODS,
    PRODUCTS_METADATA_MIN_QUANTITY.VALUE AS MIN_QUANTITY,
    PRODUCTS_METADATA_MAX_QUANTITY.VALUE AS MAX_QUANTITY ,
    PRODUCTS_METADATA_EX_REF.VALUE AS EXTERNAL_REFERENCE,
    PRICES_METADATA_COMPANY_SIZE_BUCKET.VALUE AS PRICE_COMPANY_SIZE_BUCKET,
    PRICES_METADATA_ADVANCED_EDITION.VALUE AS PRICE_MYOB_ADVANCED_EDITION,
    PRICES_METADATA_INVENTORY_ID.VALUE AS PRICE_INVENTORY_ID,
    PRICES_METADATA_EFFECTIVE_YEAR.VALUE AS PRICE_EFFECTIVE_YEAR
    from PURCHASING.PUBLISHED_PROD.STRIPE_PRICES as  STRIPE_PRICES
        LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS  as STRIPE_PRODUCTS
            ON STRIPE_PRICES.product_id = STRIPE_PRODUCTS.id
        LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS_METADATA  as PRODUCTS_METADATA_POSTING_CLASS
            ON PRODUCTS_METADATA_POSTING_CLASS.product_id = STRIPE_PRODUCTS.id 
            and PRODUCTS_METADATA_POSTING_CLASS.KEY = 'Posting Class'
        LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS_METADATA  as PRODUCTS_METADATA_PRODUCT_TYPE
            ON  PRODUCTS_METADATA_PRODUCT_TYPE.product_id = STRIPE_PRODUCTS.id 
            and  PRODUCTS_METADATA_PRODUCT_TYPE.KEY = 'Product Type'
        LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS_METADATA  as PRODUCTS_METADATA_PRODUCT_CODE
            ON  PRODUCTS_METADATA_PRODUCT_CODE.product_id = STRIPE_PRODUCTS.id 
            and  PRODUCTS_METADATA_PRODUCT_CODE.KEY = 'Product Code'
        LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS_METADATA  as PRODUCTS_METADATA_ITEM_CLASS
            ON  PRODUCTS_METADATA_ITEM_CLASS.product_id = STRIPE_PRODUCTS.id 
            and  PRODUCTS_METADATA_ITEM_CLASS.KEY =  'Item Class'
        LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS_METADATA  as PRODUCTS_METADATA_PRICE_PROTECTION_PERIODS
            ON  PRODUCTS_METADATA_PRICE_PROTECTION_PERIODS.product_id = STRIPE_PRODUCTS.id 
            and  PRODUCTS_METADATA_PRICE_PROTECTION_PERIODS.KEY =  'Price Protection Periods'
        LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS_METADATA  as PRODUCTS_METADATA_MIN_QUANTITY
            ON  PRODUCTS_METADATA_MIN_QUANTITY.product_id = STRIPE_PRODUCTS.id 
            and  PRODUCTS_METADATA_MIN_QUANTITY.KEY =  'Minimum Quantity'
         LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS_METADATA  as PRODUCTS_METADATA_MAX_QUANTITY
            ON  PRODUCTS_METADATA_MAX_QUANTITY.product_id = STRIPE_PRODUCTS.id 
            and  PRODUCTS_METADATA_MAX_QUANTITY.KEY =  'Maximum Quantity'
         LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS_METADATA  as PRODUCTS_METADATA_EX_REF
            ON  PRODUCTS_METADATA_EX_REF.product_id = STRIPE_PRODUCTS.id 
            and  PRODUCTS_METADATA_EX_REF.KEY =  'External Reference'
         LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRICES_METADATA  as PRICES_METADATA_COMPANY_SIZE_BUCKET
            ON  PRICES_METADATA_COMPANY_SIZE_BUCKET.PRICE_ID = STRIPE_PRICES.id 
            and PRICES_METADATA_COMPANY_SIZE_BUCKET.KEY =  'Company Size Bucket' 
         LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRICES_METADATA  as PRICES_METADATA_ADVANCED_EDITION
            ON  PRICES_METADATA_ADVANCED_EDITION.PRICE_ID = STRIPE_PRICES.id 
            and PRICES_METADATA_ADVANCED_EDITION.KEY =  'MYOB Advanced Edition'
         LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRICES_METADATA  as PRICES_METADATA_INVENTORY_ID
            ON   PRICES_METADATA_INVENTORY_ID.PRICE_ID = STRIPE_PRICES.id 
            and  PRICES_METADATA_INVENTORY_ID.KEY =  'Inventory ID'
         LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRICES_METADATA  as PRICES_METADATA_EFFECTIVE_YEAR
            ON   PRICES_METADATA_EFFECTIVE_YEAR.PRICE_ID = STRIPE_PRICES.id 
            and  PRICES_METADATA_EFFECTIVE_YEAR.KEY =  'Effective Year'
         LEFT JOIN PURCHASING.PUBLISHED_PROD.STRIPE_PRODUCTS_METADATA  as PRODUCTS_METADATA_SALES_ACCOUNT
            ON  PRODUCTS_METADATA_SALES_ACCOUNT.product_id = STRIPE_PRODUCTS.id 
            and  PRODUCTS_METADATA_SALES_ACCOUNT.KEY =  'Sales Account'
  )
/* {"app": "dbt", "dbt_snowflake_query_tags_version": "2.3.2", "dbt_version": "1.1.0", "project_name": "stripe", "target_name": "prod", "target_database": "OPERATIONS_ANALYTICS", "target_schema": "TRANSFORMED_PROD", "invocation_id": "1167d7ae-02a0-438c-a6d8-e30b4684dca6", "node_name": "stripe_prices_products", "node_alias": "stripe_prices_products", "node_package_name": "stripe", "node_original_file_path": "models/stripe_prices_products.sql", "node_database": "OPERATIONS_ANALYTICS", "node_schema": "TRANSFORMED_PROD", "node_id": "model.stripe.stripe_prices_products", "node_resource_type": "model", "node_meta": {}, "node_tags": [], "full_refresh": false, "which": "run", "node_refs": [], "materialized": "view"} */;